<?php

use uab\mre\app\BackupService;
use vector\ArangoORM\DB\DB;

class BackupTest extends \Tests\BaseTestCase {

    const test_coll = "test";
    protected $document_key;
    protected $document_collection;

    function setUp() {
        parent::setUp(); // TODO: Change the autogenerated stub
        DB::createCollectionIfNotExsists( self::test_coll );
        $this->document_key = DB::create(self::test_coll, [ "foo" => "bar" ] );
    }

    function tearDown() {
        parent::tearDown(); // TODO: Change the autogenerated stub
        DB::dropCollection( self::test_coll );
    }

    function testBackup(){
        BackupService::backup( self::test_coll, $this->document_key );

        $rs = DB::getByExample( self::test_coll, ["document_key" => $this->document_key ]);
        self::assertEquals( 1, $rs );
    }
}