<?php
namespace Tests\API;

/**
 * User: chris
 * Date: 5/1/17
 * Time: 1:24 AM
 */
class AssignmentTest extends \Tests\BaseTestCase
{
    private $test_user_key;
    private $test_paper_key;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->withMiddleware = false;

        $this->test_user_key = \DB\DB::create( 'users', []);
        $this->test_paper_key = \DB\DB::create('papers', []);
    }


    public function testCreateAssignment(){

        $response = $this->runApp("POST", "/assignments",
            [
                "userKey"   =>  $this->test_user_key,
                "paperKey"  =>  $this->test_paper_key
            ]);

        self::assertEquals(200, $response->getStatusCode());
    }
}